import { register } from "@tokens-studio/sd-transforms";
import StyleDictionary from "style-dictionary";

register(StyleDictionary, {
  excludeParentKeys: true,
});

const COLOR_CATEGORIES = [
  "Service",
  "Yellow",
  "Blue",
  "Neutral",
  "Green",
  "Red",
  "Label",
  "Base",
  "Line",
  "Status",
  "Action",
  "Fill",
  "Icon",
  "Surface",
];

function defaultLineHeight(px: number): string {
  if (px >= 36) return "1.3";
  if (px >= 17) return "1.4";
  return "1.5";
}

function kebab(parts: string[]): string {
  return parts.join("-").toLowerCase().replace(/\s+/g, "-");
}

StyleDictionary.registerFormat({
  name: "tailwind/v4-css",
  format: ({ dictionary }) => {
    const themeVars: string[] = [];
    const utilities: string[] = [];

    for (const token of dictionary.allTokens) {
      const [category, ...rest] = token.path;
      const key = kebab(rest);
      const value = token.$value ?? token.value;

      if (COLOR_CATEGORIES.includes(category)) {
        themeVars.push(`  --color-${category.toLowerCase()}-${key}: ${value};`);
      } else if (category === "Spacing") {
        themeVars.push(
          `  --spacing-${key}: ${typeof value === "number" ? `${value}px` : value};`,
        );
      } else if (category === "Radius") {
        themeVars.push(
          `  --radius-${key}: ${typeof value === "number" ? `${value}px` : value};`,
        );
      } else if (category === "Shadow") {
        themeVars.push(`  --shadow-${key}: ${value};`);
      } else if (category === "fontSize") {
        const px = parseFloat(String(value));
        themeVars.push(`  --text-${key}: ${px}px;`);
        themeVars.push(
          `  --text-${key}--line-height: ${defaultLineHeight(px)};`,
        );
      } else if (category === "ZIndex") {
        // v4에는 z-index theme 네임스페이스가 없으므로 커스텀 유틸리티로 생성
        utilities.push(`@utility z-${key} {\n  z-index: ${value};\n}`);
      }
    }

    return [
      "/**",
      " * AUTO-GENERATED by build-tailwind-v4-tokens.ts",
      " * 직접 수정하지 말 것 — tokens.json을 수정하고 다시 빌드하세요.",
      " */",
      "@theme {",
      "  /* 닫힌 스케일 강제: 토큰 외 spacing 배수 폴백 차단 */",
      "  --spacing: initial;",
      "  /* --spacing: initial 시 *-0 유틸리티(min-w-0 등)가 죽는 것 방지 */",
      "  --spacing-0: 0px;",
      "  --font-pretendard: Pretendard, sans-serif;",
      ...themeVars,
      "}",
      "",
      ...utilities,
      "",
    ].join("\n");
  },
});

const sd = new StyleDictionary({
  log: { verbosity: "verbose" },
  source: ["tokens.json"],
  preprocessors: ["tokens-studio"],
  platforms: {
    tailwindV4: {
      transformGroup: "tokens-studio",
      buildPath: "src/styles/",
      files: [
        {
          destination: "tokens.css",
          format: "tailwind/v4-css",
        },
      ],
    },
  },
});

async function run() {
  await sd.cleanAllPlatforms();
  await sd.buildAllPlatforms();
}

run();
